apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  selector:
    matchLabels:
      app: customer

  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: camalejao/customer
          ports:
            - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5000
  selector:
    app: customer