apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front

  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: camalejao/front
          ports:
            - containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: front-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 4000
  selector:
    app: front